version: "3.8"

volumes:
  database_volume:
    driver: local

networks:
  dbTask:
    driver: bridge


services:
  app:
    build:
      context: .docker/php
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    networks:
      - dbTask
  database:
    image: 'mysql:8'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - "database_volume:/var/lib/mysql"
    networks:
      - dbTask